import type {
  LuarizerDefManifest,
  ManifestAlias,
  ManifestClass,
  ManifestGlobal,
  ManifestLuaHook,
  ManifestMethod,
  ManifestParam,
} from '../manifest/LuarizerDefManifest.js';

function escComment(s: string): string {
  return s.replace(/\*\//g, '* /');
}

function emitMethod(className: string, m: ManifestMethod): string {
  const lines: string[] = [];
  if (m.description !== undefined && m.description.length > 0) {
    lines.push(`---${escComment(m.description)}`);
  }
  const ps = m.params ?? [];
  if (ps.length === 0) {
    if (m.returns !== undefined) {
      lines.push(`---@return ${m.returns}`);
    }
    lines.push(`function ${className}:${m.name}() end`);
    return lines.join('\n');
  }
  const recordInner = ps.map((p: ManifestParam) => `${p.name}: ${p.luaType}`).join('; ');
  lines.push(`---@param payload { ${recordInner} }`);
  if (m.returns !== undefined) {
    lines.push(`---@return ${m.returns}`);
  }
  lines.push(`function ${className}:${m.name}(payload) end`);
  return lines.join('\n');
}

function emitLuaHook(h: ManifestLuaHook): string {
  const lines: string[] = [];
  if (h.description !== undefined && h.description.length > 0) {
    lines.push(`---${escComment(h.description)}`);
  }
  lines.push(`---@param ${h.paramName} ${h.payloadLuaType}`);
  lines.push(`function ${h.name}(${h.paramName}) end`);
  return lines.join('\n');
}

function emitAlias(a: ManifestAlias): string {
  return `---@alias ${a.name} ${a.definition}`;
}

function emitClass(c: ManifestClass): string {
  const parts: string[] = [];
  parts.push('');
  if (c.description !== undefined && c.description.length > 0) {
    parts.push(`---${escComment(c.description)}`);
  }
  parts.push(`---@class ${c.name}`);
  for (const f of c.fields ?? []) {
    const d = f.description !== undefined && f.description.length > 0 ? ` ${escComment(f.description)}` : '';
    parts.push(`---@field ${f.name} ${f.luaType}${d}`);
  }
  parts.push(`${c.name} = {}`);
  for (const m of c.methods ?? []) {
    parts.push(emitMethod(c.name, m));
  }
  return parts.join('\n');
}

function emitGlobal(g: ManifestGlobal): string {
  const parts: string[] = [];
  parts.push('');
  if (g.description !== undefined && g.description.length > 0) {
    parts.push(`---${escComment(g.description)}`);
  }
  parts.push(`---@class ${g.name}Global`);
  for (const f of g.fields) {
    const d = f.description !== undefined && f.description.length > 0 ? ` ${escComment(f.description)}` : '';
    parts.push(`---@field ${f.name} ${f.luaType}${d}`);
  }
  parts.push(`---@type ${g.name}Global`);
  parts.push(`${g.name} = {}`);
  return parts.join('\n');
}

/**
 * Genera el contenido de un fichero `.d.lua` (LuaCATS) a partir del manifiesto.
 */
export function buildLuaCatsDocument(manifest: LuarizerDefManifest): string {
  const out: string[] = [];
  out.push('-- Generated by @luarizer/lua-defs — do not edit by hand.');
  out.push(`-- schemaVersion: ${String(manifest.schemaVersion)}`);
  if (manifest.headerNote !== undefined && manifest.headerNote.length > 0) {
    out.push(`-- ${escComment(manifest.headerNote)}`);
  }
  out.push('');
  out.push('---@meta');
  out.push('');

  for (const a of manifest.aliases ?? []) {
    out.push(emitAlias(a));
    out.push('');
  }

  for (const c of manifest.classes ?? []) {
    out.push(emitClass(c));
  }
  for (const h of manifest.luaHooks ?? []) {
    out.push('');
    out.push(emitLuaHook(h));
  }
  for (const g of manifest.globals ?? []) {
    out.push(emitGlobal(g));
  }

  out.push('');
  return out.join('\n');
}
